# Generated by Django 4.2.2 on 2023-09-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='price',
            new_name='prices',
        ),
    ]
