# Generated by Django 4.2.2 on 2023-08-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_categories_comments_auctions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, max_length=300)),
                ('photo', models.ImageField(upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bid_price', models.ManyToManyField(blank=True, default=models.DecimalField(decimal_places=2, max_digits=6), to='auctions.bids')),
                ('category', models.ManyToManyField(blank=True, to='auctions.categories')),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comments')),
            ],
        ),
        migrations.DeleteModel(
            name='Auctions',
        ),
    ]
