# Generated by Django 4.2.2 on 2023-09-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_price_listings_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
