# Generated by Django 4.2.2 on 2023-08-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_delete_auctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='photo',
        ),
        migrations.AlterField(
            model_name='listings',
            name='bid_price',
            field=models.ManyToManyField(blank=True, to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
