# Generated by Django 4.2.2 on 2023-08-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listings_photo_alter_listings_bid_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bid_price',
            field=models.ManyToManyField(blank=True, related_name='Bid_price', to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='Category', to='auctions.categories'),
        ),
    ]
