# Generated by Django 4.2.2 on 2023-09-11 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AlterField(
            model_name='listings',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='listings', to='auctions.comments'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='added_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
