# Generated by Django 4.2.2 on 2023-09-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_comments_user_alter_listings_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='prices',
            new_name='price',
        ),
        migrations.AddField(
            model_name='listings',
            name='bids_number',
            field=models.IntegerField(default=0),
        ),
    ]
