# Generated by Django 4.2.2 on 2023-09-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_bid_price_alter_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='active_state',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='bid_price',
            field=models.ManyToManyField(related_name='Bid_price', to='auctions.bids'),
        ),
    ]
