# Generated by Django 4.2.2 on 2023-09-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_prices_listings_price_listings_bids_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.CharField(default='admin', max_length=64),
        ),
    ]
