# Generated by Django 4.2.2 on 2023-09-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 15, 34, 54, 389174)),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='Uncategorized', max_length=64),
        ),
    ]
